apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  selector:
    matchLabels:
      app: website
  replicas: 1
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: frigus02/website:{{.ImageTag}}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "5m"
              memory: "64Mi"
            limits:
              cpu: "50m"
              memory: "128Mi"
          ports:
            - containerPort: 80
