apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: website
  annotations:
    kubernetes.io/ingress.global-static-ip-name: me-kuehle
    networking.gke.io/managed-certificates: me-kuehle
spec:
  backend:
    serviceName: website
    servicePort: 80
