name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: ./.github/workflows/build.sh
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: ./.github/workflows/deploy.sh
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
